# -*- coding: utf-8 -*-
"""lada_car_sales_clone.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GX03ZUGPdV8qTB_7NzSPrD-J5zSFpKiz

# E - Initial Analysis plan

## 1 - Data Profiling:

### Load dataset:

Method: Kaggle's API

Source: Source: LADA_car_sales - Kaggle

Link: https://www.kaggle.com/datasets/artemcheremuhin/lada-car-sales?select=lada_machines.csv
"""

# To read a CSV file from Kaggle using Kaggle's API and import it into Google Colab, follow these steps:

# import libraries:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# 1. Install Kaggle API in Google Colab

!pip install kaggle

'''
2. Get Kaggle API Credentials
Go to your Kaggle account.
In the top-right corner, click on your profile and go to Account.
Under the API section, click Create New API Token.
This will download a file called kaggle.json. This file contains your API key.
3. Upload kaggle.json to Colab
In your Google Colab, use the following code to upload the kaggle.json file.
'''


from google.colab import files
files.upload()

'''
After running the code, you can manually upload the kaggle.json file.
'''

'''
4. Set Up Kaggle API
'''

import os
# Make a directory to store Kaggle credentials
os.makedirs('/root/.kaggle', exist_ok=True)

# Move the kaggle.json file into this directory
!mv kaggle.json /root/.kaggle/

'''
5. Change Permissions for kaggle.json
'''

# Change the permissions of the kaggle.json file
!chmod 600 /root/.kaggle/kaggle.json

'''
6. Download the Dataset Using Kaggle API
Now, you can use the Kaggle API to download the dataset.
'''

!kaggle datasets download -d artemcheremuhin/lada-car-sales
# This will download a ZIP file of the dataset.

'''
7. Unzip the Dataset
After downloading the dataset, you'll need to unzip it.
'''

!unzip lada-car-sales.zip

'''
8. Read the CSV File Using Pandas
Finally, use Pandas to read the CSV file (lada_machines.csv in your case).
'''
import pandas as pd

# Load the dataset
df_buyer = pd.read_csv('lada_buyers.csv')

# Display the first few rows - 1st dataset:
df_buyer.head()

# load 2nd dataset:
df_machine = pd.read_csv('lada_machines.csv')

# Display the first few rows - 2nd dataset:
df_machine.head()

'''
Code documentation:

Summary of the Workflow:
- Install Kaggle API
- Upload kaggle.json containing your Kaggle API credentials.
- Download the dataset using the Kaggle API.
- Unzip and load the CSV file into a Pandas DataFrame directly in Google Colab
'''



